# Generated by Django 4.2.4 on 2023-08-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimecode',
            name='is_check',
            field=models.BooleanField(default=False),
        ),
    ]
