# Generated by Django 4.2.4 on 2023-09-02 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_onetimecode_is_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimecode',
            name='is_check',
        ),
    ]
