# Generated by Django 4.2.4 on 2023-09-01 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reaction',
            old_name='authorn',
            new_name='author',
        ),
    ]
