# Generated by Django 4.2.4 on 2023-09-02 16:30

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_advertisement_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', froala_editor.fields.FroalaField()),
            ],
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='status',
            field=models.CharField(choices=[('N', 'Новый'), ('A', 'Принят'), ('R', 'Отклонен')], default='N', max_length=1),
        ),
    ]
